<?php
/**
* @file
* Module file for Expreso Bolivariano Redemption
* This module connect to the redemption angular service.
*/

/**
* Implements hook_theme().
*/

function expreso_bolivariano_redemption_theme($existing, $type, $theme, $path) {

  return [
    'page_redemption_template' => [
      'template' => 'page-redemption',
      'variables' => ['user' => NULL, 'host' => NULL, 'title' => t('Redención de Puntos Viajero Expreso')],
    ],
  ];
}