<?php
/**
* @file
* Module file for Expreso Bolivariano Blocks
* 
*/
/**
* Implements hook_theme().
*/
function expreso_bolivariano_blocks_theme($existing, $type, $theme, $path) {

  return [
        'promotions_home_grid_block' => [
          'template' => 'block--promotions-home-grid',	
          'variables' => ['promotionsData' => NULL, 'promotionsMoreData' => NULL, 'title' => '', 'cache' => NULL],
        ],
        'search_trip_home' => [
          'template' => 'block--search-trip-home',  
          'variables' => ['citiesGoData' => NULL, 'citiesBackData' => NULL],
        ],
        'newsletter_home' => [
          'template' => 'block--newsletter-home',
          'variables' => ['formData' => NULL, 'cache' => NULL],
        ],
        'promotions_interns_grid_block' => [
          'template' => 'block--promotions-interns-grid',  
          'variables' => ['promotionsData' => NULL, 'promotionsMoreData' => NULL, 'title' => '', 'cache' => NULL],
        ],
        'search_package' => [
          'template' => 'block--search-package',  
          'variables' => ['formData' => NULL, 'cache' => NULL, 'title' => t('Ubicación Satelital')],
        ],
        'search_ticket' => [
          'template' => 'block--search-ticket',  
          //'variables' => ['promotionsData' => NULL, 'promotionsMoreData' => NULL, 'title' => ''],
        ],
        'contact_us' => [
          'template' => 'block--contact-us',  
          //'variables' => ['promotionsData' => NULL, 'promotionsMoreData' => NULL, 'title' => ''],
        ],
        'search_gps' => [
          'template' => 'block--search-gps',  
          'variables' => ['formData' => NULL, 'cache' => NULL, 'title' => t('Ubicación Satelital')],
        ],
        'shipping_quote' => [
          'template' => 'block--shipping-quote',  
          'variables' => ['formData' => NULL, 'cache' => NULL, 'title' => t('Cotización Envios')],
        ],
        'reservations_user_block' => [
          'template' => 'block--reservations-user',  
          'variables' => ['reservationsData' => NULL, 'title' => t('Mis Reservas'), 'cache' => NULL],
        ],
        'tickets_user_block' => [
          'template' => 'block--tickets-user',  
          'variables' => ['ticketsData' => NULL, 'title' => t('Mis Tiquetes'), 'cache' => NULL],
        ],
        'history_user_block' => [
          'template' => 'block--history-user',  
          'variables' => ['historyData' => NULL, 'title' => t('Mi Historial'), 'cache' => NULL],
        ],
        'providers_block' => [
          'template' => 'block--providers',  
          'variables' => ['formData' => NULL, 'title' => t('Certificados de Proveedores'), 'cache' => NULL],
        ],
      ];
}