<?php
/**
* @file
* Module file for Expreso Bolivariano Hello
* Este módulo crea una página estática con un mensaje de bienvenida.
*/

/**
* Implements hook_theme().
*/

function expreso_bolivariano_pages_theme($existing, $type, $theme, $path) {

  return [
    'page_agencies_template' => [
      'template' => 'page-agencies',
      'variables' => ['cities' => NULL, 'idDepts' => NULL, 'depts' => NULL, 'locations' => NULL, 'title' => t('Agencias')],
    ],
    'page_agencies_filter_template' => [
      'template' => 'page-agencies-filter',
      'variables' => ['cities' => NULL, 'idDepts' => NULL, 'depts' => NULL, 'locations' => NULL, 'agenciesList' => NULL, 'multiservicesList' => NULL, 'dataMask' => NULL, 'title' => t('Agencias Filtro')],
    ],
    'page_reservation_template' => [
      'template' => 'page-reservation',
      'variables' => ['tripsCitiesData' => NULL, 'tripsDatesData' => NULL, 'tripsDatesGoData' => NULL, 'tripsDatesBackData' => NULL, 'tripsGoData' => NULL, 'tripsBackData' => NULL, 'title' => t('Tarifas')],
    ],
    'page_selection_template' => [
      'template' => 'page-selection',
      'variables' => ['tripsCitiesData' => NULL, 'tripsDatesData' => NULL, 'attached' => NULL, 'title' => t('Selección de Sillas')],
    ],
    'page_checkout_template' => [
      'template' => 'page-checkout',
      'variables' => ['tripResumeData' => NULL, 'title' => t('Checkout')],
    ],
    'page_express_traveler_template' => [
      'template' => 'page-express-traveler',
      'variables' => ['expressTravelerData' => NULL, 'title' => t('Viajero Expreso')],
    ],
    'tab_reservation_go_template' => [
      'template' => 'tab-reservation-go',
      'variables' => ['tripsCitiesData' => NULL, 'tripsDatesData' => NULL, 'tripsDatesGoData' => NULL, 'tripsDatesBackData' => NULL, 'tripsGoData' => NULL, 'tripsBackData' => NULL, 'title' => t('Tarifas')],
    ],
    'tab_reservation_back_template' => [
      'template' => 'tab-reservation-back',
      'variables' => ['tripsCitiesData' => NULL, 'tripsDatesData' => NULL, 'tripsDatesGoData' => NULL, 'tripsDatesBackData' => NULL, 'tripsGoData' => NULL, 'tripsBackData' => NULL, 'title' => t('Tarifas')],
    ],
    'page_user_template' => [
      'template' => 'page-user',
      'variables' => ['userData' => NULL, 'title' => t('Mi Cuenta')],
    ],
    'page_user_register_template' => [
      'template' => 'page-user-register',
      'variables' => ['mail' => NULL, 'userName' => NULL, 'title' => t('Confirmación Enviada')],
    ],
    /*'page_user_reset_pass_template' => [
      'template' => 'page-user-reset-pass',
      'variables' => ['uid' => NULL, 'formData' => NULL,'title' => t('Confirmar Contraseña')],
    ],*/
    'page_notfound' => [
      'template' => 'page-notfound',
      //'variables' => ['userData' => NULL, 'title' => t('Mi Cuenta')],
    ],
  ];
}