<?php
/**
* @file
* Module file for Expreso Bolivariano Hello
* Este módulo crea una página estática con un mensaje de bienvenida.
*/

/**
* Implements hook_theme().
*/

function expreso_bolivariano_pages_theme($existing, $type, $theme, $path) {

  return [
    'page_agencies_template' => [
      'template' => 'page-agencies',
      'variables' => ['cities' => NULL, 'idDepts' => NULL, 'depts' => NULL, 'locations' => NULL, 'title' => t('Agencias')],
    ],
    'page_agencies_filter_template' => [
      'template' => 'page-agencies-filter',
      'variables' => ['cities' => NULL, 'idDepts' => NULL, 'depts' => NULL, 'locations' => NULL, 'agenciesList' => NULL, 'multiservicesList' => NULL, 'dataMask' => NULL, 'title' => t('Agencias Filtro')],
    ],
    'page_reservation_template' => [
      'template' => 'page-reservation',
      'variables' => ['tripsCitiesData' => NULL, 'tripsDatesData' => NULL, 'tripsDatesGoData' => NULL, 'tripsDatesBackData' => NULL, 'tripsGoData' => NULL, 'tripsBackData' => NULL, 'title' => t('Tarifas')],
    ],
    'page_selection_template' => [
      'template' => 'page-selection',
      'variables' => ['tripsCitiesData' => NULL, 'tripsDatesData' => NULL, 'attached' => NULL, 'title' => t('Selección de Sillas'), 'cache' => NULL],
    ],
    'page_checkout_template' => [
      'template' => 'page-checkout',
      'variables' => ['tripResumeData' => NULL, 'title' => t('Checkout'), 'cache' => NULL],
    ],
    'tab_reservation_go_template' => [
      'template' => 'tab-reservation-go',
      'variables' => ['tripsCitiesData' => NULL, 'tripsDatesData' => NULL, 'tripsDatesGoData' => NULL, 'tripsDatesBackData' => NULL, 'tripsGoData' => NULL, 'tripsBackData' => NULL, 'title' => t('Tarifas')],
    ],
    'tab_reservation_back_template' => [
      'template' => 'tab-reservation-back',
      'variables' => ['tripsCitiesData' => NULL, 'tripsDatesData' => NULL, 'tripsDatesGoData' => NULL, 'tripsDatesBackData' => NULL, 'tripsGoData' => NULL, 'tripsBackData' => NULL, 'title' => t('Tarifas')],
    ],
    'page_user_template' => [
      'template' => 'page-user',
      'variables' => ['userData' => NULL, 'title' => t('Mi Cuenta')],
    ],
    'page_user_register_template' => [
      'template' => 'page-user-register',
      'variables' => ['mail' => NULL, 'userName' => NULL, 'title' => t('Confirmación Enviada')],
    ],
    'route_schedule_bus_template' => [
      'template' => 'route-schedule-bus',
      'variables' => ['scheduleBus' => NULL, 'title' => t('Horarios Servicio')],
    ],
    'page_notfound' => [
      'template' => 'page-notfound',
    ],
    'page_gps_template' => [
      'template' => 'page-gps',
      'variables' => ['title' => t('Ubicación Satelital')],
    ],
    'page_services_template' => [
      'template' => 'page-services',
      'variables' => ['title' => t('Nuestros Servicios')],
    ],
    'route_filter_template' => [
      'template' => 'route_filter',
      'variables' => ['filterCities' => NULL, 'title' => t('Filtro Rutas')],
    ],
  ];
}